Fix indentation

diff --git a/.github/workflows/update_framework_reference.yml b/.github/workflows/update_framework_reference.yml
--- a/.github/workflows/update_framework_reference.yml
+++ b/.github/workflows/update_framework_reference.yml
@@ -66,60 +66,60 @@ jobs:
           git commit -m "$COMMIT_MSG" -m "https://github.com/ppy/osu-framework/commit/${remote_commit}" || echo "Nothing to commit"
           git push
 
-Update-reference:
-    needs: Update-framework-repo
-    if: needs.Update-framework-repo.outputs.skip_build == 'false'
-    runs-on: ubuntu-latest
-    
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-            fetch-depth: 0
-            submodules: recursive
-
-      - name: Update submodule
-        run: |
-          git submodule sync
-          git submodule update --init --recursive
-
-      - name: Bump osu!framework submodule
-        id: bump
-        run: |
-          cd osu-framework
-          git fetch origin master
-
-          if ! git pull --ff-only origin master; then
-            echo "Fast-forward failed, attempting rebase..."
-            git pull --rebase origin master
-          fi
-          cd ..
-
-      - name: Set up .NET SDK
-        uses: actions/setup-dotnet@v4
-        with:
-          dotnet-version: 8.0.x
-
-      - name: Restore dependencies
-        run: dotnet restore ./osu-framework/osu-framework.sln
-
-      - name: Install DocFX
-        run: dotnet tool update -g docfx
-
-      - name: Add DocFX to PATH
-        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH
-
-      - name: Build metadata from osu!framework
-        run: docfx metadata ./docfx.json
-
-      - name: Update API markdown info
-        run: chmod +x ./.github/workflows/writeHome.sh && ./.github/workflows/writeHome.sh ./api/Home.md ${{needs.Update-framework-repo.outputs.commit_hash}}
-
-      - name: Commit and push updated docs
-        run: |
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
-          git add api
-          COMMIT_MSG="Midnight chore: Update API references"
-          git commit -m "$COMMIT_MSG" || echo "No API doc changes"
-          git push
+  Update-reference:
+      needs: Update-framework-repo
+      if: needs.Update-framework-repo.outputs.skip_build == 'false'
+      runs-on: ubuntu-latest
+      
+      steps:
+        - name: Checkout repository
+          uses: actions/checkout@v4
+          with:
+              fetch-depth: 0
+              submodules: recursive
+  
+        - name: Update submodule
+          run: |
+            git submodule sync
+            git submodule update --init --recursive
+  
+        - name: Bump osu!framework submodule
+          id: bump
+          run: |
+            cd osu-framework
+            git fetch origin master
+  
+            if ! git pull --ff-only origin master; then
+              echo "Fast-forward failed, attempting rebase..."
+              git pull --rebase origin master
+            fi
+            cd ..
+  
+        - name: Set up .NET SDK
+          uses: actions/setup-dotnet@v4
+          with:
+            dotnet-version: 8.0.x
+  
+        - name: Restore dependencies
+          run: dotnet restore ./osu-framework/osu-framework.sln
+  
+        - name: Install DocFX
+          run: dotnet tool update -g docfx
+  
+        - name: Add DocFX to PATH
+          run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH
+  
+        - name: Build metadata from osu!framework
+          run: docfx metadata ./docfx.json
+  
+        - name: Update API markdown info
+          run: chmod +x ./.github/workflows/writeHome.sh && ./.github/workflows/writeHome.sh ./api/Home.md ${{needs.Update-framework-repo.outputs.commit_hash}}
+  
+        - name: Commit and push updated docs
+          run: |
+            git config user.name "GitHub Actions"
+            git config user.email "actions@github.com"
+            git add api
+            COMMIT_MSG="Midnight chore: Update API references"
+            git commit -m "$COMMIT_MSG" || echo "No API doc changes"
+            git push
